apiVersion: apps/v1
kind: Deployment
metadata:
  name: another-nginx-deployment
  namespace: anotherservice
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx-imagepullbackoff:1.14.2
        ports:
        - containerPort: 80