---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-git-ktes-foundation
  annotations:
        argocd.argoproj.io/sync-wave: "-5"
spec:
  generators:
    - git:
        repoURL: https://github.com/juangb/argo-manifests.git
        revision: HEAD
        directories:
          - path: manifests/foundation/*/*
  template:
    metadata:
      name: '{{path.basenameNormalized}}'  # service name. owner is not included because names longer than 64 chars are not allowed
      annotations:
        # https://argo-cd.readthedocs.io/en/latest/operator-manual/high_availability/#webhook-and-manifest-paths-annotation
        # A new commit to the Git repository invalidates cache for all applications 
        # configured in the repository that again negatively affect mono repositories 
        # with multiple applications. This annotation solves that problem.
        argocd.argoproj.io/manifest-generate-paths: .
    spec:
      project: default # TODO Use projects for further customization
      source:
        repoURL: https://github.com/juangb/argo-manifests.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basenameNormalized}}' # Same as service name. If they are different then it must be manually created.
      # Sync policy
      syncPolicy:
        automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
          prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
          selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
          allowEmpty: false # Allows deleting all application resources during automatic syncing ( false by default ).
        syncOptions:     # Sync options which modifies sync behavior
        - Validate=true # disables resource validation (equivalent to 'kubectl apply --validate=false') ( true by default ).
        - CreateNamespace=true # Namespace Auto-Creation ensures that namespace specified as the application destination exists in the destination cluster.
        - PrunePropagationPolicy=foreground # Supported policies are background, foreground and orphan.
        - PruneLast=true # Allow the ability for resource pruning to happen as a final, implicit wave of a sync operation
        # The retry feature is available since v1.7
        retry:
          limit: 5 # number of failed sync attempt retries; unlimited number of attempts if less than 0
          backoff:
            duration: 5s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
            factor: 2 # a factor to multiply the base duration after each failed retry
            maxDuration: 3m # the maximum amount of time allowed for the backoff strategy

      # Will ignore differences between live and desired states during the diff. Note that these configurations are not
      # used during the sync process.
      ignoreDifferences:
      # for the specified json pointers
      - group: apps
        kind: Deployment
        jsonPointers:
        - /spec/replicas
      # for the specified managedFields managers
      - group: "*"
        kind: "*"
        managedFieldsManagers:
        - kube-controller-manager
      # Mutated secrets (by confidant) are marked as out of sync otherwise.
      # Change an annotation to force synchronization when adding or modifying keys.
      - group: ""
        kind: Secret
        jsonPointers:
        - /data
        - /stringData
